LitorTown_House3_MapScripts::
	.byte 0


LitorTown_House3_EventScript_Man::
	msgbox LitorTown_House3_EventScript_Man_Text_0, MSGBOX_NPC
	end


LitorTown_House3_EventScript_Fisherman::
	msgbox LitorTown_House3_EventScript_Fisherman_Text_0, MSGBOX_NPC
	end


LitorTown_House3_EventScript_Man_Text_0:
	.string "Did you know that MAGIKARP are\n"
	.string "often eaten by the people?$"

LitorTown_House3_EventScript_Fisherman_Text_0:
	.string "The waters around LITOR are\n"
	.string "great areas for fishing.\p"
	.string "I've spotted a lot of different species\n"
	.string "of POKéMON already.$"
