CedarredTown_House2_MapScripts::
	.byte 0


CedarredTown_House2_EventScript_Man::
	msgbox CedarredTown_House2_EventScript_Man_Text_0, MSGBOX_NPC
	end


CedarredTown_House2_EventScript_Woman::
	msgbox CedarredTown_House2_EventScript_Woman_Text_0, MSGBOX_NPC
	end


CedarredTown_House2_EventScript_Man_Text_0:
	.string "When POKéMON battle, they eventually\n"
	.string "level up and become stronger.$"

CedarredTown_House2_EventScript_Woman_Text_0:
	.string "One of the men in the LOGGERS CABIN\n"
	.string "is my husband.\p"
	.string "He says he loves nature, but he chops\n"
	.string "down trees as his job…\p"
	.string "Don't you think that's a bit\n"
	.string "hypocritical?$"
