MurenaCity_House2_MapScripts::
	.byte 0


MurenaCity_House2_EventScript_Sailors::
	msgbox MurenaCity_House2_EventScript_Sailors_Text_0, MSGBOX_NPC
	end


MurenaCity_House2_EventScript_Woman::
	msgbox MurenaCity_House2_EventScript_Woman_Text_0, MSGBOX_NPC
	end


MurenaCity_House2_EventScript_Sailors_Text_0:
	.string "Phew…\p"
	.string "I just got back from an intense\n"
	.string "journey on the seas.\p"
	.string "My wife is happy to have me back.$"

MurenaCity_House2_EventScript_Woman_Text_0:
	.string "I'm making a meal for my husband,\n"
	.string "he must be hungry!$"
