MurenaCity_House1_MapScripts::
	.byte 0


MurenaCity_House1_EventScript_Man::
	msgbox MurenaCity_House1_EventScript_Man_Text_0, MSGBOX_NPC
	end


MurenaCity_House1_EventScript_Lass::
	msgbox MurenaCity_House1_EventScript_Lass_Text_0, MSGBOX_NPC
	end


MurenaCity_House1_EventScript_Man_Text_0:
	.string "You can really smell the salty air\n"
	.string "of the sea here.$"

MurenaCity_House1_EventScript_Lass_Text_0:
	.string "My dad always gets us TENTACOOL\n"
	.string "SKEWERS on fridays.$"
