MurenaCity_PokemonCenter_1F_MapScripts::
	.byte 0


MurenaCity_PokemonCenter_1F_EventScript_Girl::
	msgbox MurenaCity_PokemonCenter_1F_EventScript_Girl_Text_0, MSGBOX_NPC
	end


MurenaCity_PokemonCenter_1F_EventScript_Boy::
	msgbox MurenaCity_PokemonCenter_1F_EventScript_Boy_Text_0, MSGBOX_NPC
	end


MurenaCity_PokemonCenter_1F_EventScript_Girl_Text_0:
	.string "I wonder what's beyond the\n"
	.string "MURENA strait…\p"
	.string "I've only been on this part of\n"
	.string "EURUS REGION before.$"

MurenaCity_PokemonCenter_1F_EventScript_Boy_Text_0:
	.string "There's an old man at the MARKET\n"
	.string "blabbering about some old fish…\p"
	.string "He's a little creepy.$"
